# Generated by Django 4.2.3 on 2024-02-19 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rubric', '0001_initial'),
        ('sponsor', '0001_initial'),
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capsule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('image_path', models.ImageField(upload_to='images/')),
                ('video_path', models.FileField(upload_to='videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.channel')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rubric.rubric')),
                ('sponsors', models.ManyToManyField(related_name='capsule_sponsors', to='sponsor.sponsor')),
            ],
            options={
                'db_table': 'capsules',
            },
        ),
    ]
