# Generated by Django 4.2.3 on 2024-02-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0001_initial'),
        ('capsule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='sponsors',
            field=models.ManyToManyField(blank=True, related_name='capsule_sponsors', to='sponsor.sponsor'),
        ),
    ]
