# Generated by Django 4.2.3 on 2024-02-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='facebook',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='instagram',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='linkedin',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='twitter',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='vimo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
