# Generated by Django 4.2.3 on 2024-02-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0002_alter_sponsor_description_alter_sponsor_facebook_and_more'),
        ('event', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sponsors',
            field=models.ManyToManyField(blank=True, related_name='event_sponsors', to='sponsor.sponsor'),
        ),
    ]
